version: '3'

services:
###> doctrine/doctrine-bundle ###
 
  datatest:
    image: 'mysql'
    container_name: db_data_docker
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
  
  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_docker_symfony
      restart: always
      depends_on:
        - datatest
      ports:
        - 8080:80
      environment:
        PMA_HOST: datatest
      networks:
        - dev

###< doctrine/doctrine-bundle ###
networks:
  dev:
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
